#!/bin/bash

# Execute by 'moon :readme'

PACKAGES_TABLE=""

for package in packages/**/package.json; do
  name=$(jq -r '.name' "$package")
  version=$(jq -r '.version' "$package")
  description=$(jq -r '.description' "$package")

  PACKAGES_TABLE+="| $name | $version | $description |\n"
done

cat <<EOL > README.md
<!--
  * This file was autogenerated
  * If you want to change anything, do so in the project-readme.sh script
-->

<h1 align="center">
  🧺 Things
</h1>
<p align="center">
A collection of utilities and configuration files for making your life easier and reduce boilerplate.
</p>

### Packages
| Name | Version | Description |
| ---- | ------- | ----------- |
$(echo -e "$PACKAGES_TABLE")
EOL
