name: Release
on:
  release:
    types: [ released ]

jobs:
  steps:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        uses: ./.github/actions/setup

      - name: Publish
        run: |
          pnpm nx version configs
          pnpm nx version colour-palette
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
