name: Release
on:
  workflow_dispatch:

permissions: write-all

jobs:
  steps:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        uses: ./.github/actions/setup

      - name: Publish
        run: |
          npx nx version configs
          npx nx version colour-palette
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: Push to protected branch
        uses: CasperWA/push-protected@v2.14.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.ref }}
          tags: true
